# Generated by Django 2.2.16 on 2021-09-09 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('confirmation_code', models.PositiveIntegerField(verbose_name='Code')),
            ],
        ),
    ]
