# Generated by Django 2.2.16 on 2021-09-13 20:51

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='user', max_length=150, unique=True, validators=[users.models.username_validator]),
        ),
    ]
