# Generated by Django 2.2.16 on 2021-09-09 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='username',
            field=models.TextField(max_length=150, unique=True),
        ),
    ]
