# Generated by Django 2.2.16 on 2021-09-15 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20210915_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='rating',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
