# Generated by Django 2.2.16 on 2021-09-14 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20210914_2036'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='review',
            name='single_review_per_title',
        ),
    ]
