# Generated by Django 2.2.16 on 2021-09-09 19:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20210909_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(unique=True, validators=[django.core.validators.RegexValidator(message='Только буквы и цифры!', regex='^[-a-zA-Z0-9_]+$')]),
        ),
    ]
